# Generated by Django 4.2.7 on 2024-06-23 16:37

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='idioma')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='esta activo')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='prioridad')),
                ('names', models.CharField(max_length=150, verbose_name='nombres')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name': 'Mensaje | Contáctanos',
                'verbose_name_plural': 'Mensajes | Contáctanos',
                'db_table': 'apps_project_page_contact',
            },
        ),
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='idioma')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='esta activo')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='prioridad')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='contenido')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sent', 'Enviado')], default='draft', max_length=10, verbose_name='estado')),
                ('is_successful', models.BooleanField(default=False, verbose_name='envío exitoso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='mensaje de error')),
                ('open_rate', models.FloatField(default=0, verbose_name='tasa de apertura')),
                ('click_rate', models.FloatField(default=0, verbose_name='tasa de clics')),
            ],
            options={
                'verbose_name': 'Boletín',
                'verbose_name_plural': 'Boletines',
                'db_table': 'apps_project_page_newsletter',
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre de la plantilla')),
                ('header', django_ckeditor_5.fields.CKEditor5Field(verbose_name='encabezado')),
                ('footer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='pie de página')),
            ],
            options={
                'verbose_name': 'Plantilla de Boletín',
                'verbose_name_plural': 'Plantillas de Boletín',
                'db_table': 'apps_project_page_newsletter_template',
            },
        ),
        migrations.CreateModel(
            name='SubscribeNewsletterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='idioma')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='esta activo')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='prioridad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('names', models.CharField(blank=True, max_length=150, null=True, verbose_name='nombres')),
                ('cell_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='celular')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='código de país')),
            ],
            options={
                'verbose_name': 'Sucribtor - Boletín',
                'verbose_name_plural': 'Sucribtores - Boletín',
                'db_table': 'apps_project_page_subscribenewsletter',
            },
        ),
    ]
