# Generated by Django 4.2.7 on 2024-06-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettermodel',
            options={'verbose_name': 'Boletín', 'verbose_name_plural': 'Boletines'},
        ),
        migrations.AlterModelOptions(
            name='subscribenewslettermodel',
            options={'verbose_name': 'Sucribtor - Boletín', 'verbose_name_plural': 'Sucribtores - Boletín'},
        ),
        migrations.AlterField(
            model_name='newslettermodel',
            name='content',
            field=models.TextField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='newslettermodel',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío'),
        ),
        migrations.AlterField(
            model_name='newslettermodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('sent', 'Enviado')], default='draft', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='newslettermodel',
            name='subscribers',
            field=models.ManyToManyField(related_name='newsletters', to='index.subscribenewslettermodel', verbose_name='suscriptores'),
        ),
        migrations.AlterField(
            model_name='newslettermodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='subscribenewslettermodel',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='subscribenewslettermodel',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='código de país'),
        ),
        migrations.AlterField(
            model_name='subscribenewslettermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='subscribenewslettermodel',
            name='names',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombres'),
        ),
        migrations.AlterModelTable(
            name='newslettermodel',
            table='apps_project_page_newsletter',
        ),
        migrations.AlterModelTable(
            name='subscribenewslettermodel',
            table='apps_project_page_subscribenewsletter',
        ),
    ]
