# Generated by Django 4.2.7 on 2024-06-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterTemplate',
            new_name='NewsletterTemplateModel',
        ),
    ]
