# Generated by Django 4.2.7 on 2024-06-22 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_subscribenewslettermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='es', max_length=50, null=True, verbose_name='idioma')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='esta activo')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='prioridad')),
                ('names', models.CharField(max_length=150, verbose_name='nombres')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje | Contáctanos',
                'verbose_name_plural': 'Mensajes | Contáctanos',
                'db_table': 'apps_project_page_contact',
            },
        ),
    ]
